done hw4
Yuliia-Bakalova/nodejs-homework-rest-api pull request #3
Opened 2023-02-06 14:27 UTC by Yuliia-Bakalova

Перевірте, будь ласка,   ДЗ-4 :)

2023-02-06 16:40 UTC, KhYulian requested changes
Потрібні правки

2023-02-06 16:40 UTC, KhYulian commented on controllers/user.controller.js
> +      }
можна скористатися методом includes

2023-02-06 16:40 UTC, KhYulian commented on controllers/user.controller.js
> +      }
if (types.includes(subscription) {  const updatedSubscription = await Users.findByIdAndUpdate(_id, body, {
        new: true,
      }); } ...

2023-02-06 16:40 UTC, KhYulian commented on controllers/user.controller.js
> +  const subscription = body.subscription;
використовуйте деструктуризацію в таких випадках

2023-02-07 12:24 UTC, Yuliia-Bakalova commented on controllers/user.controller.js
> +      }
виправила

2023-02-07 12:24 UTC, Yuliia-Bakalova commented on controllers/user.controller.js
> +  const subscription = body.subscription;
зробила

2023-02-07 13:01 UTC, KhYulian approved these changes
Чудова робота ❤️

2023-02-07 13:01 UTC, merged